# Generated by Django 6.0.4 on 2026-04-09 09:12

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_customuser_managers_alter_customuser_avatar_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "ordering": ["username"],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="customuser",
            name="slug",
            field=models.SlugField(
                blank=True,
                help_text="Автоматически создаётся из username",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Slug для URL",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="avatar",
            field=models.ImageField(
                blank=True,
                help_text="Загрузите свой аватар",
                null=True,
                upload_to="users/avatars/",
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="birth_date",
            field=models.DateField(
                blank=True,
                help_text="Укажите дату рождения",
                null=True,
                verbose_name="Дата рождения",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                help_text="Введите номер телефона",
                max_length=128,
                null=True,
                region=None,
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="token",
            field=models.CharField(
                blank=True,
                help_text="Используется для верификации email при регистрации",
                max_length=100,
                null=True,
                verbose_name="Токен подтверждения",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Будет создан автоматически из email, если не указан",
                max_length=150,
                null=True,
                unique=True,
                verbose_name="Логин (опционально)",
            ),
        ),
    ]
