# Generated by Django 6.0.4 on 2026-04-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_customuser_options_customuser_slug_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="birth_date",
        ),
    ]
