# Generated by Django 6.0.4 on 2026-04-14 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_remove_customuser_birth_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="is_manager",
            field=models.BooleanField(
                default=False,
                help_text="Отметьте, чтобы дать права менеджера",
                verbose_name="Менеджер",
            ),
        ),
    ]
