# Generated by Django 6.0.4 on 2026-04-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_customuser_is_manager"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_manager",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="username",
            field=models.CharField(
                blank=True,
                help_text="Будет создан автоматически из email, если не указан",
                max_length=150,
                null=True,
                verbose_name="Логин (опционально)",
            ),
        ),
    ]
