# Generated by Django 6.0.4 on 2026-04-14 23:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailing", "0003_alter_mailing_options_alter_recipient_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "permissions": [
                    ("can_view_all_messages", "Может просматривать все сообщения")
                ],
                "verbose_name": "Сообщение",
                "verbose_name_plural": "Сообщения",
            },
        ),
    ]
